---
abstract: 'a framework to validate, migrate and edit configuration files'
author:
  - 'Dominique Dumont'
build_requires:
  Config::Model::Tester: '4.002'
  Config::Model::Tester::Setup: '0'
  File::Copy: '0'
  File::Spec: '0'
  IO::File: '0'
  Module::Build: '0.34'
  Test::Differences: '0'
  Test::Exception: '0'
  Test::File::Contents: '0'
  Test::Log::Log4perl: '0'
  Test::Memory::Cycle: '0'
  Test::More: '0'
  Test::Perl::Critic: '0'
  Test::Pod: '1.00'
  Test::Warn: '0.11'
  boolean: '0'
  lib: '0'
  perl: v5.20.0
configure_requires:
  Module::Build: '0.34'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.017, CPAN::Meta::Converter version 2.150010'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Config-Model
recommends:
  Fuse: '0'
  Term::ReadLine: '0'
  Text::Levenshtein::Damerau: '0'
requires:
  Carp: '0'
  Carp::Assert::More: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Encode: '0'
  English: '0'
  Fcntl: '0'
  File::HomeDir: '0'
  File::Path: '0'
  Hash::Merge: '0.12'
  JSON: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Log::Log4perl: '1.11'
  Mouse: '0'
  Mouse::Role: '0'
  Mouse::Util: '0'
  Mouse::Util::TypeConstraints: '0'
  MouseX::NativeTraits: '0'
  MouseX::StrictConstructor: '0'
  POSIX: '0'
  Parse::RecDescent: v1.90.0
  Path::Tiny: '0.070'
  Pod::POM: '0'
  Pod::Simple: '3.23'
  Pod::Text: '0'
  Regexp::Common: '0'
  Scalar::Util: '0'
  Storable: '0'
  Text::Levenshtein::Damerau: '0'
  Text::Wrap: '0'
  YAML::Tiny: '0'
  base: '0'
  feature: '0'
  open: '0'
  overload: '0'
  parent: '0'
  perl: v5.20.0
  strict: '0'
  utf8: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/dod38fr/config-model/issues
  homepage: https://github.com/dod38fr/config-model/wiki
  repository: git://github.com/dod38fr/config-model.git
version: '2.145'
x_generated_by_perl: v5.32.1
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: LGPL-2.1
